default['chef_automate']['chef_automate_fqdn'] = 'chef-dev-02.acuitylightinggroup.com'
default['chef_automate']['chef_automate_host'] = 'chef-dev-02'
default['chef_automate']['chef_automate_ip'] = '10.14.40.41'
default['chef_automate']['chef_server_fqdn'] = 'chef-dev-01.acuitylightinggroup.com'
default['chef_automate']['chef_server_host'] = 'chef-dev-01'
default['chef_automate']['chef_server_ip'] = '10.14.40.41'