default['chef_automate']['chef_automate_fqdn'] = '__automate__' + '__addomain__'
default['chef_automate']['chef_automate_host'] = '__automate__'
default['chef_automate']['chef_automate_ip'] = '__automateIP__'
default['chef_automate']['chef_server_fqdn'] = '__chef__' + '__addomain__'
default['chef_automate']['chef_server_host'] = '__chef__'
default['chef_automate']['chef_server_ip'] = '__chefIP__'